FROM mcr.microsoft.com/vscode/devcontainers/base:bullseye

ADD https://vscode.download.prss.microsoft.com/dbazure/download/stable/19e0f9e681ecb8e5c09d8784acaa601316ca4571/vscode_cli_alpine_x64_cli.tar.gz
