CREATE TYPE "public"."treehealth" AS ENUM('BAD', 'FAIR', 'GOOD', 'EXCELLENT');--> statement-breakpoint
CREATE TABLE "Role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "Tree_Species" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Tree_Species_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "Trees" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Tree_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tree_name" varchar(255),
	"tree_species" integer,
	"height" double precision,
	"health" "treehealth",
	"age" integer,
	"image" text,
	"lat" double precision,
	"lng" double precision,
	"planted_by" integer,
	"planted_on" date
);
--> statement-breakpoint
CREATE TABLE "User" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "User_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role" integer,
	"first_name" varchar(255),
	"last_name" varchar(255),
	"email" varchar(255),
	"password" varchar(255)
);
--> statement-breakpoint
ALTER TABLE "Trees" ADD CONSTRAINT "Tree_tree_species_fkey" FOREIGN KEY ("tree_species") REFERENCES "public"."Tree_Species"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Trees" ADD CONSTRAINT "Tree_planted_by_fkey" FOREIGN KEY ("planted_by") REFERENCES "public"."User"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "User" ADD CONSTRAINT "User_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."Role"("id") ON DELETE no action ON UPDATE no action;