-- Create PlantingReasons table
CREATE TABLE IF NOT EXISTS "PlantingReasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PlantingReasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now()
);

-- Create Trees_PlantingReasons junction table
CREATE TABLE IF NOT EXISTS "Trees_PlantingReasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Trees_PlantingReasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tree_id" integer NOT NULL,
	"planting_reason_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now()
);

-- Add foreign key constraints
ALTER TABLE "Trees_PlantingReasons" ADD CONSTRAINT "Trees_PlantingReasons_tree_id_Trees_id_fk" FOREIGN KEY ("tree_id") REFERENCES "Trees"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "Trees_PlantingReasons" ADD CONSTRAINT "Trees_PlantingReasons_planting_reason_id_PlantingReasons_id_fk" FOREIGN KEY ("planting_reason_id") REFERENCES "PlantingReasons"("id") ON DELETE cascade ON UPDATE no action;

-- Remove planting_reason text column from Trees table
ALTER TABLE "Trees" DROP COLUMN IF EXISTS "planting_reason";

-- Insert predefined planting reasons
INSERT INTO "PlantingReasons" ("name") VALUES
	('Event'),
	('Special Occasion (birthdays, anniversary, etc)'),
	('Reforestation'),
	('Environmental Protection (soil retention, coastal protection, etc.)'),
	('Recreational'),
	('Cultural'),
	('Other')
ON CONFLICT DO NOTHING;
