CREATE TYPE "public"."plantertype" AS ENUM('INDIVIDUAL', 'ORGANIZATION');--> statement-breakpoint
CREATE TYPE "public"."names" AS ENUM('ADMIN', 'ENVIRONMENTALIST', 'USER');--> statement-breakpoint
CREATE TYPE "public"."thresholdtype" AS ENUM('TREES_PLANTED', 'SPECIES_COUNT', 'AREA_HECTARES', 'DAYS_ACTIVE');--> statement-breakpoint
CREATE TYPE "public"."treestatus" AS ENUM('PENDING', 'APPROVED', 'DECLINED');--> statement-breakpoint
CREATE TYPE "public"."treehealth" AS ENUM('POOR', 'FAIR', 'GOOD', 'EXCELLENT');--> statement-breakpoint
CREATE TABLE "Achievement_Categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Achievement_Categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"display_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Achievements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Achievements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"icon" varchar(255),
	"threshold" integer DEFAULT 1,
	"threshold_type" "thresholdtype" NOT NULL,
	"display_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"tree_id" integer NOT NULL,
	"type" varchar(50) NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "PlantingReasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PlantingReasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" "names"
);
--> statement-breakpoint
CREATE TABLE "Tree_Species" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Tree_Species_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255),
	"is_timber" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Trees" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Tree_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tree_name" varchar(255),
	"tree_species" integer,
	"height" double precision,
	"health" "treehealth" DEFAULT 'EXCELLENT',
	"status" "treestatus" DEFAULT 'PENDING',
	"age" integer,
	"image" text,
	"lat" double precision,
	"lng" double precision,
	"planted_by" integer,
	"planted_on" date,
	"planter_type" "plantertype" DEFAULT 'INDIVIDUAL',
	"organization_name" varchar(255),
	"hashtags" text,
	"quantity" integer DEFAULT 1,
	"area_hectares" double precision,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Trees_PlantingReasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Trees_PlantingReasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tree_id" integer NOT NULL,
	"planting_reason_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "User" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "User_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role" integer,
	"first_name" varchar(255),
	"last_name" varchar(255),
	"email" varchar(255),
	"password" varchar(255),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "User_Achievements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "User_Achievements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"achievement_id" integer NOT NULL,
	"unlocked_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "User_Tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "User_Tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"fcm_token" text NOT NULL,
	"device_info" varchar(255),
	"last_updated" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "Achievements" ADD CONSTRAINT "Achievements_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."Achievement_Categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Notifications" ADD CONSTRAINT "Notifications_user_id_User_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Notifications" ADD CONSTRAINT "Notifications_tree_id_Trees_id_fk" FOREIGN KEY ("tree_id") REFERENCES "public"."Trees"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Trees" ADD CONSTRAINT "Tree_tree_species_fkey" FOREIGN KEY ("tree_species") REFERENCES "public"."Tree_Species"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Trees" ADD CONSTRAINT "Tree_planted_by_fkey" FOREIGN KEY ("planted_by") REFERENCES "public"."User"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Trees_PlantingReasons" ADD CONSTRAINT "Trees_PlantingReasons_tree_id_Trees_id_fk" FOREIGN KEY ("tree_id") REFERENCES "public"."Trees"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Trees_PlantingReasons" ADD CONSTRAINT "Trees_PlantingReasons_planting_reason_id_PlantingReasons_id_fk" FOREIGN KEY ("planting_reason_id") REFERENCES "public"."PlantingReasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "User" ADD CONSTRAINT "User_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."Role"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "User_Achievements" ADD CONSTRAINT "User_Achievements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "User_Achievements" ADD CONSTRAINT "User_Achievements_achievement_id_fkey" FOREIGN KEY ("achievement_id") REFERENCES "public"."Achievements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "User_Tokens" ADD CONSTRAINT "User_Tokens_user_id_User_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;